### ISSUE TITLE
Please don't include GCC version in installed file paths

### ISSUE THREAD

**Issue by yurivict** [toml-f/toml-f#51]
This and many your other projects include strings like ```GNU-10.3.0```:
```
$ find /usr/local/include/ -name GNU-10.3.0
/usr/local/include/mctc-lib/GNU-10.3.0
/usr/local/include/mstore/GNU-10.3.0
/usr/local/include/multicharge/GNU-10.3.0
/usr/local/include/toml-f/GNU-10.3.0
/usr/local/include/tblite/GNU-10.3.0
/usr/local/include/s-dftd3/GNU-10.3.0
/usr/local/include/dftd4/GNU-10.3.0
```

This causes ports/packages to break when gcc version is changed because plist would change and ports would need to be updated.

**Comment by awvwgk** [comment]
Since Fortran compiler are not necessarily ABI compatible this is the wanted behavior.

However, it is notable that the GFortran ABI has been stable now since version 9, meaning this could be reconsidered now. I'm unsure whether there is a reliable way to extract the version of the module files at configure time to use this for tagging rather than the compiler version number which might be too tightly pinned.

**Comment by awvwgk** [comment]
The module directory is set always in `config/CMakeLists.txt`:

https://github.com/toml-f/toml-f/blob/f066ec6e7fb96d8faf83ab6614ee664a26ad8d57/config/CMakeLists.txt#L16-L20

feel free to patch the generation of the module directory string if this is an actual problem. I could also offer in the future to allow overwriting a cached variable.
